In [1]:
# Libraries
import numpy as np
import sympy.physics.vector as vctr

In [2]:
# Calculation
A = np.array([2, 3, 4]) # 2i + 3j + 4k
B = np.array([4, -2, 6]) # 4i - 2j + 6k
print(f"A = {A}")
print(f"B = {B}")
result = A + B
print(f"{A} + {B} = {result}")
result = A - B
print(f"{A} - {B} = {result}")
result = np.dot(A, B)
print(f"{A} . {B} = {result}")
result = np.cross(A, B)
print(f"{A} x {B} = {result}")

A = [2 3 4]
B = [ 4 -2  6]
[2 3 4] + [ 4 -2  6] = [ 6  1 10]
[2 3 4] - [ 4 -2  6] = [-2  5 -2]
[2 3 4] . [ 4 -2  6] = 26
[2 3 4] x [ 4 -2  6] = [ 26   4 -16]


In [3]:
R = vctr.ReferenceFrame("R")
PHI = R[0] * R[1] * R[2] # PHI = xyz
# A = 2xy(i) + xyz(j) - yz(k)
A = 2 * R[0] * R[1] * R.x + R[0] * R[1] * R[2] * R.y - R[1] * R[2] * R.z
a = vctr.gradient(PHI, R)
b = vctr.divergence(A, R)
c = vctr.curl(A, R)
d = vctr.divergence(PHI * A, R)
e = vctr.curl(PHI * A, R)

In [4]:
PHI

R_x*R_y*R_z

In [5]:
A

2*R_x*R_y*R.x + R_x*R_y*R_z*R.y - R_y*R_z*R.z

In [6]:
a

R_y*R_z*R.x + R_x*R_z*R.y + R_x*R_y*R.z

In [7]:
b

R_x*R_z + R_y

In [8]:
c

(-R_x*R_y - R_z)*R.x + (-2*R_x + R_y*R_z)*R.z

In [9]:
d

2*R_x**2*R_y*R_z**2 + 2*R_x*R_y**2*R_z

In [10]:
e

(-2*R_x**2*R_y**2*R_z - 2*R_x*R_y*R_z**2)*R.x + (2*R_x**2*R_y**2 + R_y**2*R_z**2)*R.y + (-4*R_x**2*R_y*R_z + 2*R_x*R_y**2*R_z**2)*R.z