In [1]:
# Libraries
import numpy as np

# Initialize and Declaration
# -2x + 3y + z = 9
# 3x + 4y - 5z = 0
# x - 2y + z = -4
matrix = np.array([[-2, 3, 1], [3, 4, -5], [1, -2, 1]]) # Variable Coefficient
constant = np.array([[9], [0], [-4]]) # Constant
det_matrix = np.linalg.det(matrix) # determinant

In [2]:
det_matrix

-22.000000000000004

In [3]:
# Calculation
n = len(matrix)
m = np.zeros((n, 1))
for i in range(0, n):
    for j in range(0, n):
        matrix[j, i] = constant[j][0]
    print(f'Matrix M{i + 1}:')
    print(matrix)
    det_matrix_i = np.linalg.det(matrix)
    m[i][0] = det_matrix_i / det_matrix
    matrix = np.array([[-2, 3, 1], [3, 4, -5], [1, -2, 1]])

Matrix M1:
[[ 9  3  1]
 [ 0  4 -5]
 [-4 -2  1]]
Matrix M2:
[[-2  9  1]
 [ 3  0 -5]
 [ 1 -4  1]]
Matrix M3:
[[-2  3  9]
 [ 3  4  0]
 [ 1 -2 -4]]


In [4]:
print("\nSolution:")
print(m)
print("or")
print(f'x = {m[0]}; y = {m[1]}; z = {m[2]}')


Solution:
[[-1.]
 [ 2.]
 [ 1.]]
or
x = [-1.]; y = [2.]; z = [1.]
